apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ln722s919-go
  janus-idp.io/tekton: ln722s919-go
  backstage.io/kubernetes-id: ln722s919-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ln722s919-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
